### PR TITLE
Dashboard: World Map at player Y level

### PR DESCRIPTION
**Pull request by Kenny-Hui**
Adds the ability to render the world map at the player's current Y level, toggleable with buttons at the bottom right (#199)

image

image

image

**Related changes:**
- Light Levels are calculated when rendering in Underground mode
- Change the Dashboard Map to use NativeImage instead (Each chunk is a 16x16 texture), updated every 1s and disposed when dashboard closed.

### CODE REVIEW

**Comment by Kenny-Hui** [comment]
Actually maybe we should find the nearest air block first before projecting the view

This should resemble closer to other minimap mods (and Spectator mode) where solid areas are culled and cave system are revealed (Instead of the now endless stone and andesite)

**Comment by Ultimate-USA-YT** [comment]
Love this. Will make Building Large Scale Underground Stations Easier

**Comment by JiaqiYi** [comment]
not a good idea.when you want to edit a station,you have to fly to a y level instead of edit a y=100station at y=200

**Comment by Kenny-Hui** [comment]
> not a good idea.when you want to edit a station,you have to fly to a y level instead of edit a y=100station at y=200

Not true, the Y level mode is not activated by default.
Dashboard map will behave exactly as they were before, you have to explicitly toggle it via the buttons at the bottom.

Although this PR is a bit dated by now, might have to work it later.

**Pull request merged**
