### PR TITLE
World Region Feature (Finished)

### PR DESCRIPTION
**Pull request by ExtremeMakerX**
### **This adds World Region buttons and refresh button on the train selection.**

This makes it easier to find which train world category you're looking for!
It's functional and consistent! Also, you won't see this on the boat siding screen.

### CODE REVIEW

**Comment by kettle-7** [comment]
custom trains?
and I suggest do by continent like Asia, Americas, Europe, Australasia, Africa etc

not worth having Antarctica tbh

**Comment by ExtremeMakerX** [comment]
> custom trains? and I suggest do by continent like Asia, Americas, Europe, Australasia, Africa etc
> 
> not worth having Antarctica tbh

Kettle-7 These other regions are not necessary since there are no trains no like that in the MTR mod and longer spellings for the regions are too big. That's the reason why I went with Asia, USA and UK. 

World Region custom resource compatibility. I will do it in a future pull request. I just wanted to focus on the core.

**Comment by epmgr** [comment]
> > custom trains? and I suggest do by continent like Asia, Americas, Europe, Australasia, Africa etc
> > 
> > not worth having Antarctica tbh
> 
> Kettle-7 These other regions are not necessary since there are no trains no like that in the MTR mod and longer spellings for the regions are too big. That's the reason why I went with Asia, USA and UK. 
> 
> World Region custom resource compatibility. I will do it in a future pull request. I just wanted to focus on the core.

Also, some custom trains may not necessarily be from Asia, the USA or the UK.

**Comment by jonafanho** [comment]
Thank you for your contribution. I am tracking this work separately in #864 as the implementation in 4.0.0 is quite different.

**Pull request closed without merging**
