### PR TITLE
4.0.0:Added new rail connectors.

### PR DESCRIPTION
**Pull request by YYLWZDXPGD**
# 简体中文
原 #781 
1. 金连接器，时速100
2. 蓝冰连接器，时速250
3. 下界合金连接器，时速400
目前此计划已经完成
# English
From #781 
1. Gold connector,100km/h
2. Blue ice connector,250km/h
3. Netherint connector,400km/h
This project was done.

### CODE REVIEW

**Comment by Ultimate-USA-YT** [comment]
There's a Reason No Rails Go above 300 km/h

**Comment by YYLWZDXPGD** [comment]
> There's a Reason No Rails Go above 300 km/h
Why？

**Comment by YYLWZDXPGD** [comment]
If the train stop,the chunk will start good rendering.

**Comment by YYLWZDXPGD** [comment]
Due to conflict with  #901 , I will close this PR

**Comment by DarkMasterXPGD** [comment]
Reopen in #976

**Pull request closed without merging**
